### ISSUE TITLE
Help wanted!

### ISSUE THREAD

**Issue by tlycken** [tlycken/Contour.jl#37]
When I started this project, in close collaboration with @darwindarak, I had the opportunity to spend a lot of my coding time with Julia, as I was actively using it myself. For quite some time now, this is no longer the case, and Julia programming has been pushed back on my priority list to the place of "hobbies I can't quite find the time for".

This was fine as long as the packages I maintained were relatively stable, with little activity in issues and pull requests, but lately I've felt that there is more and more going on that I'm unable to keep up with. Thus, I feel I'm no longer doing as well as I'd like as a maintainer, and I think it's time to pass the baton to someone else.

I'm opening this issue as a call for a discussion on where this package should live. Would you like to assume ownership? Do you know of an organization that would?

**Comment by bjarthur** [comment]
besides Gadfly, what other packages use Contour?

**Comment by tlycken** [comment]
@bjarthur I honestly don't know. I remember there was a visualizer for the package ecosystem somewhere, but I can't recall where. I originally broke the functionality out of Gadfly because I needed it by itself, so there might be others who have the same need - thus, such a visualization might not be a full representation of actual usages.

However, the library is very stable at the moment - we have an implementation of marching squares that seems to work very well, and not much else. Interested in taking over? :)

**Comment by bjarthur** [comment]
i'm happy to lend a hand, but it'd be best to do so through an organization.  JuliaGeometry perhaps?  @simondanisch

**Comment by SimonDanisch** [comment]
Sure! I'm actually using Contour.jl as well...

**Comment by tlycken** [comment]
JuliaGeometry sounds like a good fit for this, yes. In order to transfer ownership I need access to create repositories in that organization - are you able to set that up, @SimonDanisch?

**Comment by tlycken** [comment]
@KristofferC kindly invited me into the JuliaGeometry organization, so I'll now transfer the repository there, hoping that things like #38 can be handled with a little less friction than today :)

As the core code itself is pretty robust by now, I doubt there will be need for any deep knowledge of the algorithm to keep this package up-to-date - more likely, this code could be merged into (or replaced by new implementations in) another package, e.g. Meshes.jl. I'll close this for now, thanks for all the help!
